require("symbols-outline").setup(
    {
        highlight_hovered_item = true,
        show_guides = true,
        auto_preview = true,
        position = 'right',
        relative_width = true,
        width = 25,
        auto_close = true,
        show_numbers = true,
        show_relative_numbers = true,
        show_symbol_details = true,
        preview_bg_highlight = 'Pmenu',
        autofold_depth = 1,
        auto_unfold_hover = true,
        fold_markers = { '', '' },
        wrap = false,
        keymaps = { -- These keymaps can be a string or a table for multiple keys
            close = { "<Esc>", "q" },
            goto_location = "<Cr>",
            focus_location = "o",
            hover_symbol = "<C-space>",
            toggle_preview = "K",
            rename_symbol = "r",
            code_actions = "a",
            fold = "h",
            unfold = "l",
            fold_all = "W",
            unfold_all = "E",
            fold_reset = "R",
        },
        lsp_blacklist = {},
        symbol_blacklist = {},
        symbols = {
            File = { icon = "F", hl = "@text.uri" },
            Module = { icon = "M", hl = "@namespace" },
            Namespace = { icon = "ns", hl = "@namespace" },
            Package = { icon = "P", hl = "@namespace" },
            Class = { icon = "C", hl = "@type" },
            Method = { icon = "m", hl = "@method" },
            Property = { icon = "", hl = "@method" },
            Field = { icon = "f", hl = "@field" },
            Constructor = { icon = "ctor", hl = "@constructor" },
            Enum = { icon = "enum", hl = "@type" },
            Interface = { icon = "I", hl = "@type" },
            Function = { icon = "fn", hl = "@function" },
            Variable = { icon = "var", hl = "@constant" },
            Constant = { icon = "k", hl = "@constant" },
            String = { icon = "str", hl = "@string" },
            Number = { icon = "#", hl = "@number" },
            Boolean = { icon = "⊨", hl = "@boolean" },
            Array = { icon = "[]", hl = "@constant" },
            Object = { icon = "o", hl = "@type" },
            Key = { icon = "key", hl = "@type" },
            Null = { icon = "NULL", hl = "@type" },
            EnumMember = { icon = "", hl = "@field" },
            Struct = { icon = "S", hl = "@type" },
            Event = { icon = "Ev", hl = "@type" },
            Operator = { icon = "+", hl = "@operator" },
            TypeParameter = { icon = "type", hl = "@parameter" },
            Component = { icon = "", hl = "@function" },
            Fragment = { icon = "", hl = "@constant" },
        },
    }
)


vim.keymap.set("n", "<C-b>", ":SymbolsOutline<CR>")
